COAP_TEST_SERVER_IP = $$(COAP_TEST_SERVER_IP)
!isEmpty(COAP_TEST_SERVER_IP) {
    DEFINES += COAP_TEST_SERVER_IP=\\\"$${COAP_TEST_SERVER_IP}\\\"
    message(CoAP plugtest server IP set to $$COAP_TEST_SERVER_IP)
}
